---
scan: 135
root_folder: null
save_folder: null
data_dir: null
sample_name: "S"
comment: ""
debug: False

beamline: "P10"
actuators: null
is_series: True
rocking_angle: "outofplane"
sdd: 1.84
energy: 8170
beam_direction: [1, 0, 0]
outofplane_angle: 42.6093
inplane_angle: -0.5783
tilt_angle: 0.00537
sample_offsets: [0, 0, 90, 0]
specfile_name: ""

custom_scan: False 
custom_motors:
delta: "inplane_angle"
gamma: 'outofplane_angle'
theta: 1.0540277
phi: -4.86
custom_images: np.arange(11353, 11453, 1) # tricky
custom_monitor: np.ones(len(custom_images)) # tricky

detector: "Merlin"
linearity_func: null
x_bragg: 1577
y_bragg: 833
roi_detector: null
photon_threshold: 0
photon_filter: "loading"
background_file: null
high_threshold: 1000000
hotpixels_file: null
flatfield_file: null
pixel_size: 55
nb_pixel_x: null
nb_pixel_y: null
template_imagefile: "_master.h5"

use_rawdata: True
interp_method: "xrayutilities"
fill_value_mask: 0
sample_offsets: null
sdd: 0.50678
energy: 9000
xrayutilities:
sample_inplane: [1, 0, 0]
sample_outofplane: [0, 0, 1]
offset_inplane: 0
cch1: 208
cch2: 208
detrot: 0
tiltazimuth: 360
tilt: 0

binning: [1, 2, 2]
bin_during_loading: False
frames_pattern: null
filtered_data: False
peak_method: "maxcom"
normalize_flux: "monitor"
flag_interact: False
background_plot: "0.5"
centering: "max"
fix_bragg: []
fix_size: []
center_fft: "skip"
pad_size: []
normalize_flux: "monitor"
mask_zero_event: False
flag_medianfilter: "skip"
medfilt_order: 7
reload_previous: False
reload_orthogonal: False
preprocessing_binning: [1, 1, 1]
save_rawdata: False
save_to_npz: True
save_to_mat: False
save_to_vti: False
save_asint: False

sort_method: "variance/mean"
correlation_threshold: 0.90
original_size: [150, 256, 500]
phasing_binning: [1, 1, 1]
preprocessing_binning: [1, 2, 2]
output_size: [100, 100, 100]
voxel_sizes_parameters:
keep_size: False
fix_voxel: 10
data_frame: "detector"
ref_axis_q: "y"
save_frame: "laboratory"
isosurface_strain: 0.2
strain_method: "default"
phase_offset: 0
phase_offset_origin: null
offset_method: "mean"
centering_method: "max_com"
correct_refraction: True
optical_path_method: "threshold"
dispersion: 5.0328e-05
absorption: 4.1969e-06
threshold_unwrap_refraction: 0.05
simu_flag: False
invert_phase: True 
flip_reconstruction: False
phase_ramp_removal: "gradient"
threshold_gradient: 1.0
save_raw: False
save_support: False
save: True
debug: False
roll_modes: [0, 0, 0]
align_axis: False
ref_axis: "y"
axis_to_align: [0, 1, 0]
strain_range: 0.003
phase_range: 1.57
grey_background: True
tick_spacing: 50
tick_direction: "inout"
tick_length: 3
tick_width: 1
get_temperature: False
reflection: [1, 1, 1]
reference_spacing: null
reference_temperature: null
avg_space: "reciprocal_space"
avg_threshold: 0.90
hwidth: 0
apodize_flag: False
apodize_window: "blackman"
mu: [0.0, 0.0, 0.0]
sigma: [0.30, 0.30, 0.30]
alpha: [1, 1, 1]