# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pip-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Display Python location
      run: | 
        python_path=$(which python  2>&1)
        echo "Python path: $python_path"
        site_packages="Site packages path: $( cd "$(dirname "$(dirname "$python_path")")"/lib/python3.10/site-packages ; pwd -P )"
        echo $site_packages

    - name: Cache dependencies
      id: myCache
      uses: actions/cache@v2
      with:
        path: ${{env.LD_LIBRARY_PATH}}/python3.10/site-packages
        key: ${{ runner.os }}-pip-v0-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      if: steps.myCache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Format the code with black
      run: python -m black bcdi --check

    - name: Check imports with isort
      run: python -m isort --profile black bcdi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. Use the default of 88 chars
        python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Type check with mypy
      run: python -m mypy bcdi

    - name: Install the package
      run: python -m pip install -e .

    - name: Test with pytest
      run: python -m pytest
